version: "3.5"
networks:
  banshee:
    name: banshee
services: 
  envoy:
    networks:
      - banshee
    image: envoyproxy/envoy:v1.16.2
    command: "envoy -c /etc/envoy/envoy-xds.yaml"
    volumes:
      - ../envoy-xds.yaml:/etc/envoy/envoy-xds.yaml
    expose:
      - "8443"
      - "9000"
      - "9003"
    ports:
      - "8443:8443"
      - "9000:9000"  
      - "9003:9003"  