version: "3.5"
networks:
  banshee:
    name: banshee
services:
  consul-xds:
    networks:
      - banshee
    build:
      context: .
    expose:
      - "8053"
    ports:
      - "8053:8053"
    volumes:
      - ./scripts/wait-for-it.sh:/usr/bin/wait-for-it.sh