FROM alpine:3.9.2
WORKDIR /opt/app
ADD app .
RUN apk update

ENV PORT=8053 \
	LOG_LEVEL=INFO \
	CONSUL_CLIENT_PORT=8500 \
	CONSUL_CLIENT_HOST= \
	CONSUL_DC=dc1 \
	CONSUL_TOKEN= \
	WATCHED_SERVICE=
EXPOSE ${PORT}
CMD ./app