version: "3.5"
networks:
  banshee:
    name: banshee
services:  
  solr1:
    networks:
      - banshee
    image: solr:6.6.6
    user: root
    ports:
      - "8983:8983"
    links:
      - zook1
    volumes:
      - ./scripts/wait-for-it.sh:/usr/bin/wait-for-it.sh
    command: >
      bash -c '/usr/bin/wait-for-it.sh -h zook1 -p 2181 -t 0; server/scripts/cloud-scripts/zkcli.sh -z zook1:2181/solr -cmd bootstrap -solrhome /opt/solr/server/solr
      && /opt/solr/bin/solr -c -f -z zook1:2181/solr -force'
    depends_on:
      - zook1
  solr2:
    networks:
      - banshee
    image: solr:6.6.6
    user: root
    ports:
      - "8984:8983"
    links:
      - zook1
    volumes:
      - ./scripts/wait-for-it.sh:/usr/bin/wait-for-it.sh
    command: >
      bash -c '/usr/bin/wait-for-it.sh -h zook1 -p 2181 -t 0; server/scripts/cloud-scripts/zkcli.sh -z zook1:2181/solr -cmd bootstrap -solrhome /opt/solr/server/solr
      && /opt/solr/bin/solr -c -f -z zook1:2181/solr -force'
    depends_on:
      - zook1
  zook1:
    networks:
      - banshee
    image: jplock/zookeeper:3.4.10
    ports:
      - "2181:2181"
  